### ISSUE TITLE
I2C Read of Specific register address

### ISSUE THREAD

**Issue by ironmike87** [armstrap/armstrap-pyvirtualbench#14]
It is possible I missed it in the example, but how does the I2C code read from a specified register?
I see where the slave address is configured, that is straight forward.
If I wanted to read register 0x31 from device address 0x50, how would I do that?

**Comment by armstrap** [comment]
Hi ironmike87,

Typically, you can write the register address to the i2c device (telling it which register to select), and then perform a read to read the contents of that register.

See
https://github.com/armstrap/armstrap-pyvirtualbench/blob/master/pyvirtualbench/pyvirtualbench.py#L2320

Have you considered perhaps writing such an example to illustrate this?  Since you haven't reported an issue with the source, I'm going to go ahead and close this issue.
